### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Grass311** [Sweenus/SimplySkills#96] opened 2024-06-17 16:51 UTC
Right now Simply skills crashes my game because it does not work with the newest version of Spell engine which was updated recently

**Comment by Sweenus** [comment] 2024-06-20 22:14
Yes, you need to downgrade. Spell Engine released API breaking changes and Simply Skills hasn't updated yet.

**Comment by VitaminJake** [comment] 2024-06-25 03:35
You should close this issue. Grass, when you make a ticket, put some damn information in besides "doesn't work". It makes you look stupid and then people don't know that the issue is already being tracked when they look through the list. Sorry for making a duplicate, Sweenus

**Comment by Sweenus** [comment] 2024-06-30 07:46
This is resolved as of the latest version (1.5.0)

**Closed as completed by Sweenus** 2024-06-30 07:46 UTC
